<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>net.mattlabs.mauvelist</groupId>
    <artifactId>mauvelist-root</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>

    <properties>
        <revision>4.0.0</revision>
        <maven.compiler.release>25</maven.compiler.release>
        <!-- Enforce Unicode when compiling Java -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <modules>
        <!-- Folder name, not artifactId -->
        <module>api</module>
        <module>discord</module>
        <module>plugin</module>
        <module>current</module>
    </modules>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.16.0</version>
                    <configuration>
                        <!-- Specifies minimum Java version and Unicode for compile and runtime -->
                        <encoding>${project.build.sourceEncoding}</encoding>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
