<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.mattlabs.mauvelist</groupId>
        <artifactId>mauvelist-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>discord</artifactId>

    <!-- Project dependencies -->

    <dependencies>
        <!-- For Common -->
        <dependency>
            <groupId>net.mattlabs.mauvelist</groupId>
            <artifactId>common</artifactId>
            <version>${revision}</version>
        </dependency>
        <!-- For JDA -->
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>6.7.0</version>
            <exclusions>
                <exclusion>
                    <groupId>club.minnced</groupId>
                    <artifactId>opus-java</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.crypto.tink</groupId>
                    <artifactId>tink</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- For SLF4J (For JDA)-->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>2.0.19</version>
        </dependency>
    </dependencies>

</project>