<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.mattlabs.mauvelist</groupId>
        <artifactId>mauvelist-root</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>common</artifactId>

    <!-- Project dependencies -->

    <repositories>
        <!-- For Configurate -->
        <repository>
            <id>sponge</id>
            <url>https://repo.spongepowered.org/maven</url>
        </repository>
    </repositories>

    <dependencies>
        <!-- For Configurate -->
        <dependency>
            <groupId>org.spongepowered</groupId>
            <artifactId>configurate-hocon</artifactId>
            <version>4.2.0</version>
        </dependency>
    </dependencies>

</project>